# Generated by Django 3.2.5 on 2021-10-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marathi_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marathi_name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('captured_date', models.DateTimeField(auto_now_add=True)),
                ('image_location', models.CharField(max_length=300)),
                ('image_height', models.DecimalField(decimal_places=0, max_digits=5)),
                ('image_width', models.DecimalField(decimal_places=0, max_digits=5)),
                ('is_annotated', models.BooleanField(default=False)),
                ('centerLatitude', models.DecimalField(decimal_places=8, default=None, max_digits=15)),
                ('centerLongitude', models.DecimalField(decimal_places=8, default=None, max_digits=15)),
                ('is_approved', models.BooleanField(default=True)),
                ('zoom_level', models.DecimalField(decimal_places=0, default=None, max_digits=3, null=True)),
                ('derived_from_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gmapv3.image')),
            ],
        ),
        migrations.CreateModel(
            name='JSMappedWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=15, default=None, max_digits=20, null=True)),
                ('longitude', models.DecimalField(decimal_places=15, default=None, max_digits=20, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('work_name', models.TextField(blank=True, null=True)),
                ('dataOfYear', models.CharField(default=None, max_length=10)),
                ('date_recorded', models.DateField(blank=True, null=True)),
                ('time_recorded', models.TimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_marked', models.BooleanField(null=True)),
                ('dept_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gmapv3.deptname')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gmapv3.districtname')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marathi_name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JSMappedWorksImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapped_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gmapv3.image')),
                ('jsmappedwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gmapv3.jsmappedworks')),
            ],
        ),
        migrations.AddField(
            model_name='jsmappedworks',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gmapv3.worktype'),
        ),
        migrations.CreateModel(
            name='GMapMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_date', models.DateTimeField(auto_now_add=True)),
                ('locality', models.CharField(default=None, max_length=50)),
                ('district', models.CharField(default=None, max_length=50)),
                ('geometryJSON', models.TextField()),
                ('ground_truthing_done', models.BooleanField(default=False)),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gmapv3.image')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_label', models.CharField(blank=True, max_length=200)),
                ('annotation_date', models.DateTimeField(auto_now_add=True)),
                ('geometryJSON', models.TextField()),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gmapv3.image')),
            ],
        ),
    ]
