# Generated by Django 3.2.5 on 2021-10-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv3', '0001_initial'),
    ]

    operations = [
    	migrations.RunSQL("""
            INSERT INTO "Gmapv3_jsmappedworks" (
                id,
                latitude,
                longitude,
                remark,
                work_name,
                "dataOfYear",
                date_recorded,
                time_recorded,
                address,
                is_marked,
                dept_name_id,
                district_id,
                work_type_id
            )
            SELECT
                id,
                latitude,
                longitude,
                remark,
                work_name,
                "dataOfYear",
                date_recorded,
                time_recorded,
                address,
                is_marked,
                dept_name_id,
                district_id,
                work_type_id
            FROM
                "Gmapv2_jsmappedworks";
        """, reverse_sql="""
            INSERT INTO "Gmapv3_jsmappedworks" (
                id,
                latitude,
                longitude,
                remark,
                work_name,
                "dataOfYear",
                date_recorded,
                time_recorded,
                address,
                is_marked,
                dept_name_id,
                district_id,
                work_type_id
            )
            SELECT
                id,
                latitude,
                longitude,
                remark,
                work_name,
                dataOfYear,
                date_recorded,
                time_recorded,
                address,
                is_marked,
                dept_name_id,
                district_id,
                work_type_id
            FROM
                "Gmapv2_jsmappedworks";
        """)
    ]
