# Generated by Django 3.2.5 on 2021-10-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv3', '0002_auto_20211010_0145'),
    ]

    operations = [
    	migrations.RunSQL("""
            INSERT INTO "Gmapv3_image" (
                id,
                image_name,
                captured_date,
                image_location,
                image_height,
                image_width,
                is_annotated,
                "centerLatitude",
                "centerLongitude",
                is_approved,
                zoom_level,
                derived_from_image_id                
            )
            SELECT
                id,
                image_name,
                captured_date,
                image_location,
                image_height,
                image_width,
                is_annotated,
                "centerLatitude",
                "centerLongitude",
                is_approved,
                zoom_level,
                derived_from_image_id
            FROM
                "Gmapv2_image";
        """, reverse_sql="""
            INSERT INTO "Gmapv3_image" (
                id,
                image_name,
                captured_date,
                image_location,
                image_height,
                image_width,
                is_annotated,
                "centerLatitude",
                "centerLongitude",
                is_approved,
                zoom_level,
                derived_from_image_id
            )
            SELECT
                id,
                image_name,
                captured_date,
                image_location,
                image_height,
                image_width,
                is_annotated,
                "centerLatitude",
                "centerLongitude",
                is_approved,
                zoom_level,
                derived_from_image_id
            FROM
                "Gmapv2_image";
        """)
    ]
