# Generated by Django 3.2.5 on 2021-10-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv3', '0003_auto_20211010_0407'),
    ]
    operations = [
    	migrations.RunSQL("""
            INSERT INTO "Gmapv3_annotation" (
                id,
                class_label,
                annotation_date,
                "geometryJSON",
                source_image_id
            )
            SELECT
                id,
                class_label,
                annotation_date,
                "geometryJSON",
                source_image_id
            FROM
                "Gmapv2_annotation";
        """, reverse_sql="""
            INSERT INTO "Gmapv3_annotation" (
                id,
                class_label,
                annotation_date,
                "geometryJSON",
                source_image_id
            )
            SELECT
                id,
                class_label,
                annotation_date,
                "geometryJSON",
                source_image_id
            FROM
                "Gmapv2_annotation";
        """)
    ]
