# Generated by Django 3.2.5 on 2021-10-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv3', '0005_auto_20211010_0443'),
    ]

    operations = [
    	migrations.RunSQL("""
            INSERT INTO "Gmapv3_jsmappedworksimage" (
                id,
                mapped_date,
                image_id,
                jsmappedwork_id
            )
            SELECT
                id,
                mapped_date,
                image_id,
                jsmappedwork_id
            FROM
                "Gmapv2_jsmappedworksimage";
        """, reverse_sql="""
            INSERT INTO "Gmapv3_jsmappedworksimage" (
                id,
                mapped_date,
                image_id,
                jsmappedwork_id
            )
            SELECT
                id,
                mapped_date,
                image_id,
                jsmappedwork_id
            FROM
                "Gmapv2_jsmappedworksimage";
        """)
    ]
